language: node_js
node_js:
  - "10.15.2"
dist: trusty
sudo: required

services:
  - docker

script: "echo 'Building Docker image with tags'"

after_success:
  - export DEPLOY_TIMESTAMP=`date +'%Y%m%d-%H%M%S'`
  # Creating a custom tag for the docker image in addition to the default "latest" tag.
  - docker build -t demo:$DEPLOY_TIMESTAMP-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH -t web-frontend:latest .
  # script: chmod +x ./scripts/* && ./scripts/execute.sh <Cluster Namespace> <Container Registry Namespace>
  - chmod +x ./build_and_push_image.sh || travis_terminate 4

deploy:
  provider: openshift
  server: https://c100-e.us-east.containers.cloud.ibm.com:31217
  token: OLHiAQNW30OQCyKGNCmzDoStW1mgSnVZis82X6q1_WU
  project: csankara-in
  app: web-frontend
  edge: true

